#!/usr/bin/env bash
brew_prefix=$(brew --prefix)

cat <<EOF
# I don't want to have to type 'ggrep'
export PATH=$brew_prefix/opt/grep/libexec/gnubin:\$PATH

# Need the man pages for the GNU grep
export MANPATH=$brew_prefix/opt/grep/libexec/gnuman:\$MANPATH
EOF
