#!/usr/bin/env bash
brew_prefix=$(brew --prefix)

cat <<EOF
# I'm used to the GNU version of utils
export PATH=$brew_prefix/opt/coreutils/libexec/gnubin:\$PATH
export PATH=$brew_prefix/opt/util-linux/bin:\$PATH


# Need the man pages for the GNU coreutils
export MANPATH=$brew_prefix/opt/coreutils/libexec/gnuman:\$MANPATH
export MANPATH=$brew_prefix/opt/util-linux/share/man/:\$MANPATH
EOF
