#!/usr/bin/env bash
brew_prefix=$(brew --prefix 2>/dev/null)
if [[ "$brew_prefix" ]]; then
  export NVM_DIR="${brew_prefix}/opt/nvm"
elif [[ -f ~/.nvm/nvm.sh ]]; then
  export NVM_DIR="$HOME/.nvm"
fi

NVMSH=${NVM_DIR}/nvm.sh

if [[ -f $NVMSH ]]; then
  cat <<EOF
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
EOF
fi
